version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: votesphere-frontend
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
        networks:
            - votesphere-networks

networks:
    votesphere-networks:
        driver: bridge
